name: Build JPY wheels

on: push

jobs:
  bdist-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py:
          - '3.4'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
        arch:
          - 'x64'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
          architecture: ${{ matrix.arch }}
          cache: 'pip'

      - uses: actions/setup-java@v3
        id: setup-java
        with:
          distribution: 'temurin'
          java-version: '8'

      - run: pip install -r .github/requirements.txt

      - run: python setup.py bdist_wheel
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}

      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.py }}-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*.whl
          retention-days: 1
